Repository drspangle/infidel-sensor, pull requests merged in 2021-04, with the labels that each got.

#8 infidel Sensor with Table in EEPROM and Programming over I2C
  firmware/Host_ee_prog.ino
  firmware/Infidel_release_ee.ino
  firmware/README.md
  firmware/host_to_sensor_arduino.PNG
Labels: documentation, enhancement

#10 Update Lever.stl
  mechanical/LeverDB.f3d
  mechanical/stl/Lever.stl
Labels: bug

#22 Change grubscrew M5 to M6
  README.md
Labels: bug, documentation

#28 fix capacitor grounds not connected
  electrical/smt/KiCAD/filaSens.kicad_pcb
Labels: bug
